# Generated by Django 4.0.4 on 2022-04-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=225)),
                ('price', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
